"""Initial: Session and RAGDocument tables

Revision ID: 748867262a9f
Revises: 
Create Date: 2025-12-21 23:21:13.937422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '748867262a9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('character', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deck_path', sa.Text(), nullable=True),
    sa.Column('deck_format', sa.String(length=10), nullable=True),
    sa.Column('deck_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('slide_contents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pitch_transcript', sa.Text(), nullable=True),
    sa.Column('qa_transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('realtime_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('council_dialog', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('verdict', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('investor_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('rag_documents')
    # ### end Alembic commands ###
